project:
  type: website
  output-dir: docs
website:
  title: Intro Biostatistics Resources
  reader-mode: true
  repo-url: https://github.com/haleykgrant/IntroBiostatResources
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Home
        href: index.qmd
        contents:       
          - text: Tutorials
            href: index.qmd#Tutorials
          - text: Shiny Apps
            href: index.qmd#shiny-apps
  navbar:
    right:
    - about.qmd
    - icon: github
      href: https://github.com/haleykgrant/IntroBiostatResources
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css:
    - styles.css
    - include/webex.css
    include-after-body: include/webex.js
editor: visual
